sylius_ui:
    events:
        monsieurbiz.settings.admin.update:
            blocks:
                _content: '@MonsieurBizSyliusSettingsPlugin/Crud/Edit/_content.html.twig'
        monsieurbiz.settings.admin.update.form:
            blocks:
                _form: '@MonsieurBizSyliusSettingsPlugin/Crud/Edit/_form.html.twig'
        sylius.admin.layout.javascripts:
            blocks:
                monsieurbiz_settings:
                    template: '@MonsieurBizSyliusSettingsPlugin/Layout/_javascripts.html.twig'
