services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false
        Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType:
            autowire: false
        Sylius\Component\Resource\Model\ResourceInterface:
            autowire: false

    MonsieurBiz\SyliusSettingsPlugin\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    MonsieurBiz\SyliusSettingsPlugin\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    monsieurbiz.settings.metadata_registry:
        class: MonsieurBiz\SyliusSettingsPlugin\Settings\Metadata\Registry

    MonsieurBiz\SyliusSettingsPlugin\Settings\Metadata\RegistryInterface: '@monsieurbiz.settings.metadata_registry'

    monsieurbiz.settings.registry:
        class: MonsieurBiz\SyliusSettingsPlugin\Settings\Registry
    
    MonsieurBiz\SyliusSettingsPlugin\Settings\RegistryInterface: '@monsieurbiz.settings.registry' 
