name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:

  tests:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0']
        mysql: [5.7]
        sylius: ["~1.8.0", "~1.9.0", "~1.10.0"]
        exclude:
          - php: 8.0
            sylius: "~1.8.0"
          - php: 8.0
            sylius: "~1.9.0"

    steps:
      - uses: actions/checkout@v2

      - name: Switch PHP
        run: |
          sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}
          php -v

      - uses: actions/cache@v1
        with:
          path: /home/runner/.composer/cache
          key: composer2-php:${{ matrix.php }}-${{ github.sha }}
          restore-keys: composer2-php:${{ matrix.php }}-

      - run: mkdir -p /home/runner/{.composer/cache,.config/composer}
        if: steps.cache-composer.outputs.cache-hit != 'true'
              
      - name: Composer v2
        run: sudo composer self-update --2

      - name: Install symfony CLI
        run: |
          curl https://get.symfony.com/cli/installer | bash
          echo ${HOME}/.symfony/bin >> $GITHUB_PATH

      - name: Restrict Sylius version
        run: composer require "sylius/sylius:${{ matrix.sylius }}" --no-update --no-scripts --no-interaction

      - name: Validate composer.json
        run: composer validate --strict --no-check-all

      - name: Composer Github Auth
        run: composer config -g github-oauth.github.com ${{ github.token }}

      - name: Update dependencies
        run: composer update --prefer-stable --prefer-dist --no-progress --no-suggest --no-scripts

      - name: PHP CS Fixer
        run: make test.phpcs

#      - name: Lint container
#        run: make test.container

      - name: Lint twig
        run: make test.twig

      - name: Lint Yaml
        run: make test.yaml

#      - name: PHPunit
#        run: ./vendor/bin/phpunit

    services:

      mysql:
        image: percona:${{ matrix.mysql }}
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true


  sylius:

    runs-on: ubuntu-latest

    env:
      SYMFONY_ENDPOINT: http://127.0.0.1/

    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0']
        mysql: [5.7]
        sylius: ["~1.8.0", "~1.9.0", "~1.10.0"]
        exclude:
          - php: 8.0
            sylius: "~1.8.0"
          - php: 8.0
            sylius: "~1.9.0"

    steps:
      - name: Setup some envs
        run: |
          echo "DATABASE_URL=mysql://root@127.0.0.1/sylius" >> $GITHUB_ENV

      - name: Setup PHP
        run: |
          sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}
          echo "date.timezone=UTC" >> /tmp/timezone.ini
          sudo mv /tmp/timezone.ini /etc/php/${{ matrix.php }}/cli/conf.d/timezone.ini
          echo ${{ matrix.php }} > .php-version

      - name: Setup timezone
        run: |
          echo "date.timezone=UTC" >> /tmp/timezone.ini; \
          sudo mv /tmp/timezone.ini /etc/php/${{ matrix.php }}/cli/conf.d/timezone.ini

      - uses: actions/cache@v1
        with:
          path: /home/runner/.composer/cache
          key: composer2-php:${{ matrix.sylius }}-${{ matrix.php }}-${{ github.sha }}
          restore-keys: composer2-php:${{ matrix.sylius }}-${{ matrix.php }}-
    
      - run: mkdir -p /home/runner/{.composer/cache,.config/composer}
        if: steps.cache-composer.outputs.cache-hit != 'true'

      - name: Composer v2
        run: sudo composer self-update --2

      - uses: actions/checkout@v2
        with:
          path: plugin

      # Run the server at the start so it can download the recipes!
      - name: Run standalone symfony flex server
        run: |
          echo ${{ github.token }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          docker run --rm --name flex -d -v $PWD/plugin/recipe:/var/www/flex/var/repo/private/monsieurbiz/sylius-settings-plugin -p 80:80 docker.pkg.github.com/monsieurbiz/docker/symfony-flex-server:latest contrib official
          docker ps

      - uses: actions/cache@v1
        with:
          path: /home/runner/.composer/cache
          key: composer2-php:${{ matrix.sylius }}-${{ matrix.php }}-${{ github.sha }}
          restore-keys: composer2-php:${{ matrix.sylius }}-${{ matrix.php }}-

      - name: Install symfony CLI
        run: |
          curl https://get.symfony.com/cli/installer | bash
          echo ${HOME}/.symfony/bin >> $GITHUB_PATH

      - name: Composer Github Auth
        run: composer config -g github-oauth.github.com ${{ github.token }}

      - name: Install Sylius-Standard
        run: |
          composer create-project --prefer-dist --no-scripts --no-progress sylius/sylius-standard sylius "${{ matrix.sylius }}"

      - name: Init database
        working-directory: ./sylius
        run: |
          php bin/console doctrine:database:create --if-not-exists
          php bin/console doctrine:migr:migr -n

      - name: Add path repository
        working-directory: ./sylius
        run: |
          composer config repositories.plugin '{"type": "path", "url": "../plugin/"}'

      - name: Allow contrib recipes
        working-directory: ./sylius
        run: composer config extra.symfony.allow-contrib true

      - name: Allow unsecure localhost flex server
        working-directory: ./sylius
        run: composer config secure-http false

      - name: Install plugin
        working-directory: ./sylius
        run: |
          composer config --unset platform.php
          cp -Rv ../plugin/recipes/dev/config/* ./config/
          composer require monsieurbiz/sylius-settings-plugin="*@dev"

      - name: Show flex server logs
        run: docker logs --tail 100 flex

      - name: Update database schema
        working-directory: ./sylius
        run: |
          php bin/console doctrine:migr:migr -n
          php bin/console doctrine:schema:validate

      - name: Install Sylius
        working-directory: ./sylius
        run: php bin/console sylius:install -n

      - name: Run fixtures
        working-directory: ./sylius
        run: php bin/console sylius:fixtures:load -n default

    services:

      mysql:
        image: percona:${{ matrix.mysql }}
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
